name: Add a Event
description: Add this event to the list
title: 'Add [EVENT NAME]'
labels: [add event]
body:
  - type: markdown
    attributes:
      value: '**Share the current and relevant details**'
  - type: input
    id: title
    attributes:
      label: Event Name
      placeholder: 'e.g.: Nextjs Conf'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Short Description of the Event ( 20 words )
      placeholder: 'At Next.js Conf 2022, learn to build better and scale faster'
    validations:
      required: true
  - type: input
    id: date-time
    attributes:
      label: Event Date and Time
      placeholder: 'e.g.: 15/11/2021 10:00 IST'
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Event Page Link
      placeholder: 'e.g.: https://nextjs.org/'
    validations:
      required: true
  - type: input
    id: theme
    attributes:
        label: Themes
        placeholder: 'DEVOPS, BLOCKCHAIN, SECURITY'
  - type: markdown
    attributes:
      value: '## Social Links'
  - type: input
    id: facebook
    attributes:
      label: Facebook
      placeholder: 'e.g.: https://facebook.com/'
  - type: input
    id: github
    attributes:
      label: Github
      placeholder: 'e.g.: https://github.com/'
  - type: input
    id: instagram
    attributes:
      label: Instagram
      placeholder: 'e.g.: https://instagram.gg/'
  - type: input
    id: Linkedin
    attributes:
      label: LinkedIn
      placeholder: 'e.g.: https://linkedin.com/'
  - type: input
    id: twitter
    attributes:
        label: Twitter
        placeholder: 'e.g.: https://twitter.com/'
  - type: input
    id: discord
    attributes:
        label: Discord
        placeholder: 'e.g.: https://discord.gg'
  - type: input
    id: landingpage-link
    attributes:
        label: Other Link
        placeholder: 'e.g.: https://chandraprakash.codes/'
